## <span style="color: #ffffff;"><b>Projeto Final de Conclusão de Módulo</b></span>

### <span style="color: #05f509;"><b>Cenário</b></span>

Você é um analista de dados contratado por uma loja de varejo com o objetivo de analisar os dados de vendas e fornecer insights que possam ajudar a melhorar as operações e o desempenho da loja.

### <span style="color: #05f509;"><b>Conjunto de Dados</b></span>

Os dados utilizados para a análise incluem informações diárias sobre vendas, categorias de produtos, preços, quantidades vendidas, descontos aplicados e algumas características de clientes (idade e renda) do último ano de operação da empresa. Os dados estão no arquivo vendas_supermercado_com_cliente.csv.

### <span style="color: #05f509;"><b>Objetivo</b></span>

Sua missão é avaliar os dados e responder a 10 perguntas levantadas pela equipe de marketing, que estão listadas abaixo:

Para isso, devemos iniciar importando o pandas:

In [1]:
import pandas as pd

O arquivo a ser utilizado será o **vendas_supermercado_com_cliente.csv** que será importado com o seguinte comando e será chamado de df:

In [2]:
df = pd.read_csv('vendas_supermercado_com_cliente.csv')

A seguir teremos o DataFrame a ser trabalhado na análise:

In [3]:
df

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.00,164.6000,49,2715.61
1,2023-01-01,Bananas,Alimentos Frescos,2.39,4,0.00,9.5600,29,2280.15
2,2023-01-01,Laranjas,Alimentos Frescos,8.38,5,0.00,41.9000,67,4419.56
3,2023-01-01,Tomates,Alimentos Frescos,2.03,15,0.00,30.4500,29,3809.17
4,2023-01-01,Alface,Alimentos Frescos,37.14,14,0.00,519.9600,24,1013.42
...,...,...,...,...,...,...,...,...,...
20070,2023-12-31,Produtos de higiene para pets,Pet Shop,26.62,15,0.21,315.4470,39,2475.82
20071,2023-12-31,Panelas,Utilidades Domésticas,33.00,19,0.15,532.9500,25,4766.49
20072,2023-12-31,Talheres,Utilidades Domésticas,27.60,12,0.29,235.1520,65,3367.68
20073,2023-12-31,Copos,Utilidades Domésticas,15.35,13,0.25,149.6625,42,3823.50
20074,2023-12-31,"Produtos descartáveis (pratos, copos, talheres)",Utilidades Domésticas,32.06,6,0.11,171.2004,59,3303.47

Ao analisar as informações dos dados com `info()`, verifiquei que o tipo de dados da coluna **Data** estão como string:

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20075 entries, 0 to 20074
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         20075 non-null  str
 1   Produto      20075 non-null  str
 2   Categoria    20075 non-null  str
 3   Preço        20075 non-null  float64
 4   Quantidade   20075 non-null  int64
 5   Desconto     20075 non-null  float64
 6   Total_Venda  20075 non-null  float64
 7   Idade        20075 non-null  int64
 8   Renda        20075 non-null  float64
dtypes: float64(4), int64(2), str(3)
memory usage: 1.4 MB

Como utilizarei a data para realizar a análise foi necessário a conversão desse tipo de dado para `datetime`

In [5]:
df['Data'] = pd.to_datetime(df['Data'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20075 entries, 0 to 20074
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         20075 non-null  datetime64[us]
 1   Produto      20075 non-null  str
 2   Categoria    20075 non-null  str
 3   Preço        20075 non-null  float64
 4   Quantidade   20075 non-null  int64
 5   Desconto     20075 non-null  float64
 6   Total_Venda  20075 non-null  float64
 7   Idade        20075 non-null  int64
 8   Renda        20075 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(2), str(2)
memory usage: 1.4 MB

Agora com os dados tratados e a identificação que não há valores nulos, começarei a análise de dados.

#### <span style="color: #acffa6;"><b>1 - Quais foram as categorias de produtos mais vendidos e em quais meses eles tiveram o maior pico de vendas?</b></span>

Verificando as categorias mais vendidas:

In [6]:
df.groupby('Categoria', as_index=False)['Quantidade'].sum().sort_values(ascending=False, by='Quantidade')

                     Categoria  Quantidade
0            Alimentos Frescos       54755
7        Produtos de Mercearia       21857
3            Laticínios e Ovos       18602
6          Produtos de Limpeza       18448
5  Produtos de Higiene Pessoal       18374
1                      Bebidas       18206
4                     Pet Shop       18081
2                   Congelados       18051
8        Utilidades Domésticas       14530

Abaixo agrupei para saber por mês e por categoria o total vendido e já deixei decrescente. Além disso mudei nome da coluna para mês.

In [7]:
categ_mes = df.groupby([df['Data'].dt.month, 'Categoria'],as_index=False)['Quantidade'].sum().sort_values(ascending=False, by='Quantidade')
categ_mes = categ_mes.rename(columns={'Data': 'Mes'})
categ_mes

    Mes              Categoria  Quantidade
18    3      Alimentos Frescos        4832
54    7      Alimentos Frescos        4739
81   10      Alimentos Frescos        4700
45    6      Alimentos Frescos        4663
99   12      Alimentos Frescos        4595
..  ...                    ...         ...
53    6  Utilidades Domésticas        1222
80    9  Utilidades Domésticas        1182
26    3  Utilidades Domésticas        1160
17    2  Utilidades Domésticas        1110
98   11  Utilidades Domésticas        1062

[108 rows x 3 columns]

Com todas as categorias somadas mês a mês e ordenadas em ordem decrescente, agrupei novamente por categoria e usei o `head(1)` para trazer apenas a primeira linha (maior valor) de cada categoria, trazendo também o mês que foi mais vendido:

In [8]:
resultado = categ_mes.groupby('Categoria').head(1)
resultado.sort_values(by='Categoria')

     Mes                    Categoria  Quantidade
18     3            Alimentos Frescos        4832
1      1                      Bebidas        1651
83    10                   Congelados        1649
21     3            Laticínios e Ovos        1681
49     6                     Pet Shop        1586
41     5  Produtos de Higiene Pessoal        1641
87    10          Produtos de Limpeza        1650
106   12        Produtos de Mercearia        1950
107   12        Utilidades Domésticas        1308

#### <span style="color: #acffa6;"><b>2 - Qual a média de vendas diárias por categoria de produto?</b></span>

In [29]:
media_dia_categoria = df.groupby(['Data', 'Categoria'])['Quantidade'].sum().groupby('Categoria').mean().reset_index()
media_dia_categoria = media_dia_categoria.rename(columns={'Quantidade': 'Média de Vendas Dia'})
media_dia_categoria

                     Categoria  Média de Vendas Dia
0            Alimentos Frescos           150.013699
1                      Bebidas            49.879452
2                   Congelados            49.454795
3            Laticínios e Ovos            50.964384
4                     Pet Shop            49.536986
5  Produtos de Higiene Pessoal            50.339726
6          Produtos de Limpeza            50.542466
7        Produtos de Mercearia            59.882192
8        Utilidades Domésticas            39.808219

#### <span style="color: #acffa6;"><b>3 - Quais produtos apresentam a maior sazonalidade nas vendas (ex.: frutas e vegetais, sorvetes)?</b></span>

In [42]:
mensal = df.groupby(['Produto', df['Data'].dt.to_period('M')])['Quantidade'].sum().reset_index()
media_geral = mensal.groupby('Produto', as_index=False)['Quantidade'].mean()
media_geral
sazonalidade[df['sazo']] = mensal / media_geral

TypeError: unsupported operand type(s) for /: 'str' and 'str'

#### <span style="color: #acffa6;"><b>4 - Quais as faixas etárias contribuíram mais para as vendas totais? Para responder essa pergunta, crie uma coluna com a faixa etária, considerando: entre 18 e 35 (jovem), entre 36 e 59 (adulto) e acima de 60 anos (idoso).</b></span>

Criei a coluna nova de acordo com os parâmetros:

In [43]:
df['Faixa_Etaria'] = df.loc[(df['Idade'] >= 18) & (df['Idade'] <= 35), 'Faixa_Etaria'] = 'Jovem'; df.loc[(df['Idade'] >= 36) & (df['Idade'] <= 59), 'Faixa_Etaria'] = 'Adulto'; df.loc[df['Idade'] >= 60, 'Faixa_Etaria'] = 'Idoso'
df

,Data,Produto,Categoria,Preço,Quantidade,Desconto,Total_Venda,Idade,Renda,Faixa_Etaria
0,2023-01-01,Maçãs,Alimentos Frescos,16.46,10,0.00,164.6000,49,2715.61,Adulto
1,2023-01-01,Bananas,Alimentos Frescos,2.39,4,0.00,9.5600,29,2280.15,Jovem
2,2023-01-01,Laranjas,Alimentos Frescos,8.38,5,0.00,41.9000,67,4419.56,Idoso
3,2023-01-01,Tomates,Alimentos Frescos,2.03,15,0.00,30.4500,29,3809.17,Jovem
4,2023-01-01,Alface,Alimentos Frescos,37.14,14,0.00,519.9600,24,1013.42,Jovem
...,...,...,...,...,...,...,...,...,...,...
20070,2023-12-31,Produtos de higiene para pets,Pet Shop,26.62,15,0.21,315.4470,39,2475.82,Adulto
20071,2023-12-31,Panelas,Utilidades Domésticas,33.00,19,0.15,532.9500,25,4766.49,Jovem
20072,2023-12-31,Talheres,Utilidades Domésticas,27.60,12,0.29,235.1520,65,3367.68,Idoso
20073,2023-12-31,Copos,Utilidades Domésticas,15.35,13,0.25,149.6625,42,3823.50,Adulto
20074,2023-12-31,"Produtos descartáveis (pratos, copos, talheres)",Utilidades Domésticas,32.06,6,0.11,171.2004,59,3303.47,Adulto

Agrupando por faixa etária para saber o total em vendas (R$)

In [44]:
df.groupby('Faixa_Etaria', as_index=False)['Total_Venda'].sum().sort_values(ascending=False, by='Total_Venda').round(2)

  Faixa_Etaria  Total_Venda
0       Adulto   2102041.77
2        Jovem   1537183.38
1        Idoso   1297252.20

#### <span style="color: #acffa6;"><b>5 - Qual é a relação entre a idade dos clientes e a categoria de produto mais vendida para cada?</b></span>

Em todas as faixas etárias a categoria mais vendida foi a de Alimentos Frescos sendo o grupo de Adultos a que mais consumiu.

In [ ]:
categ_faixa_etaria = df.groupby(['Faixa_Etaria','Categoria'], as_index=False)['Quantidade'].sum().sort_values(ascending=False, by=['Faixa_Etaria', 'Quantidade'])

categ_faixa_etaria

#### <span style="color: #acffa6;"><b>6 - Qual a distribuição das vendas ao longo dos dias da semana?</b></span>

#### <span style="color: #acffa6;"><b>7 - Como as vendas mensais se comparam antes e durante a Black Friday?</b></span>

In [15]:
categ_mes['data_especial'] = 'normal'
categ_mes.loc[categ_mes['Mes'] == 11, 'data_especial'] = 'black_friday'

comparacao_black = categ_mes.groupby('data_especial')['Quantidade'].mean()
comparacao_black = comparacao_black.rename(columns=['Quantidade':'Media'])

SyntaxError: invalid syntax (881126341.py, line 5)

#### <span style="color: #acffa6;"><b>8 - Qual é o ticket médio (valor médio das vendas) por faixa etária e como ele varia entre diferentes categorias de produto?</b></span>

#### <span style="color: #acffa6;"><b>9 - Comparando a semana da “Black Friday” com a do Natal, qual semana a empresa teve melhores desempenhos em relação à média de vendas?</b></span>

#### <span style="color: #acffa6;"><b>10 - Qual foi o impacto das promoções (descontos aplicados) nas vendas? Quais produtos tiveram o maior aumento nas vendas durante as promoções?</b></span>